version: '2'
services:
  nginx-filebeat:
    domainname: nginx-filebeat.com
    hostname: nginx-filebeat
    container_name: nginx-filebeat
    restart: always
    image: nginx-filebeat:v0
    ports:
      - "443:443"
      - "8099:80"
    environment:
      - DOMAIN=xxxx.i-vectors.com
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/log_serve.conf:/etc/nginx/conf.d/log_serve.conf
      - ./conf.d/filebeat.yml:/filebeat.yml
      - ./conf.d/certs:/certs
    # command:
      # sh -c "nginx && bundle exec thin -p 3000"
    # networks:
    #   app_net:
    #     ipv4_address: 172.16.0.34

# networks:
#   app_net:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#       - subnet: 172.16.0.0/24
#         gateway: 172.16.0.1
